import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      // _id: '1',
      name: 'Sneakers White',
      slug: 'Sneakers White',
      category: 'Shoe',
      image: '/images/Sneakers White.jpg', // 679px × 829px
      price: 12900.99,
      countInStock: 10,
      brand: 'Sneakers',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '1',
      name: 'Sneakers',
      slug: 'Sneakers',
      category: 'Shoe',
      image: '/images/Sneakers.jpg', // 679px × 829px
      price: 12900.99,
      countInStock: 10,
      brand: 'Sneakers',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'straightJean',
      slug: 'straightJean',
      category: 'Pant',
      image: '/images/straightJean.jpg',
      price: 7250.00,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '3',
      name: 'Vans Fun Floral Classic Jurniors Slip Sneakers On Shoes',
      slug: 'Vans Fun Floral Classic Jurniors Slip Sneakers On Shoes',
      category: 'Shoe',
      image: '/images/Vans Fun Floral Classic Jurniors Slip Sneakers On Shoes.jpg',
      price: 15000,
      countInStock: 15,
      brand: 'Vans',
      rating: 4.5,
      numReviews: 14,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '4',
      name: 'Vans Fun Floral Classic Jurniors Slip On Shoes',
      slug: 'Vans Fun Floral Classic Jurniors Slip On Shoes',
      category: 'Shoe',
      image: '/images/Vans Fun Floral Classic Jurniors Slip On Shoes.jpg',
      price: 9800.09,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '1',
      name: 'Vintage Suit',
      slug: 'Vintage-suit',
      category: 'Suit',
      image: '/images/p5.jpg', // 679px × 829px
      price: 35000.99,
      countInStock: 1,
      brand: 'Vintage',
      rating: 4.5,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '2',
      name: 'Adidas Sweater',
      slug: 'adidas-',
      category: 'Shirts',
      image: '/images/psweat.jpg',
      price: 17500,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '3',
      name: 'Blue shirt',
      slug: 'nike-blue shirt',
      category: 'Shirts',
      image: '/images/p7.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '4',
      name: 'India Sarri',
      slug: 'India Sarri',
      category: 'Lady',
      image: '/images/p8.jpg',
      price: 45000.00,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '1',
      name: 'Female jean Jacket',
      slug: 'Female jean Jacket',
      category: 'Shirts',
      image: '/images/p9.jpg', // 679px × 829px
      price: 9500.00,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Gown',
      slug: 'adidas-fit-Gown',
      category: 'Shirts',
      image: '/images/p10.jpg',
      price: 25000.99,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '3',
      name: 'Crinky Slim Top',
      slug: 'Crinky Slim Top',
      category: 'Shirts',
      image: '/images/p11.jpg',
      price: 5999.99,
      countInStock: 35,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '4',
      name: 'Adidas UNisex Shirt',
      slug: 'adidas-Unisex-shirt',
      category: 'Shirts',
      image: '/images/p12.jpg',
      price: 6599.99,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '1',
      name: 'Addidas Cloudfoam Pure 2.0 Running Shoes black',
      slug: 'Addidas Cloudfoam',
      category: 'Shoe',
      image: '/images/Addidas Cloudfoam Pure 2.0 Running Shoes black.jpg', // 679px × 829px
      price: 12500,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Addidas Cloudfoam Pure 2.0 Running Shoes white',
      slug: 'Addidas Cloudfoam Pure 2.0 Running Shoes white',
      category: 'Shoe',
      image: '/images/Addidas Cloudfoam Pure 2.0 Running Shoes white.jpg',
      price: 25000,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '3',
      name: 'Berechnung Vance Shoe',
      slug: 'Berechnung Vance Shoe',
      category: 'Shoe',
      image: '/images/Berechnung Vance Shoe.jpg',
      price: 25000,
      countInStock: 15,
      brand: 'Vans',
      rating: 4.5,
      numReviews: 14,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '4',
      name: 'Black Girls Flower Printed Top',
      slug: 'Black Girls Flower Printed Top',
      category: 'Lady',
      image: '/images/Black Girls Flower Printed Top.jpg',
      price: 6599.99,
      countInStock: 15,
      brand: 'Kiok',
      rating: 4.5,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '1',
      name: 'black Gucci jacket',
      slug: 'black Gucci jacket',
      category: 'Jacket',
      image: '/images/black Gucci jacket.jpg', // 679px × 829px
      price: 12000,
      countInStock: 10,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '2',
      name: 'blackcrop',
      slug: 'blackcrop',
      category: 'Lady',
      image: '/images/blackcrop.jpg',
      price: 2599.99,
      countInStock: 10,
      brand: 'Croppie',
      rating: 4.0,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '3',
      name: 'blackhoodie',
      slug: 'blackhoodie',
      category: 'Hoodie',
      image: '/images/blackhoodie.jpg',
      price: 9050.99,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '4',
      name: 'RedHoodie',
      slug: 'Redhoodie',
      category: 'Hoodie',
      image: '/images/p6.jpg',
      price: 6500.99,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '1',
      name: 'Blue sneakers',
      slug: 'Blue sneakers',
      category: 'Shoe',
      image: '/images/Blue sneakers.jpg', // 679px × 829px
      price: 12000.99,
      countInStock: 10,
      brand: 'Sneaker',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'croptop',
      slug: 'croptop',
      category: 'Lady',
      image: '/images/croptop.jpg',
      price: 2500.09,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '3',
      name: 'Bluecroptop',
      slug: 'Bluecroptop',
      category: 'Lady',
      image: '/images/bluecroptop.jpg',
      price: 3999.99,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '4',
      name: 'female flower top',
      slug: 'female flower top',
      category: 'Lady',
      image: '/images/female flower top.jpg',
      price: 6500.00,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '1',
      name: 'Floral SandarCamemore 2021',
      slug: 'Floral SandarCamemore 2021',
      category: 'Shoe',
      image: '/images/Floral SandarCamemore 2021.jpg', // 679px × 829px
      price: 12000.00,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Flower mixed white office shirt for ladies',
      slug: 'Flower mixed white office shirt for ladies',
      category: 'Lady',
      image: '/images/Flower mixed white office shirt for ladies.jpg',
      price: 2500.99,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '3',
      name: 'Flower mixed white office shirt for ladies',
      slug: 'Flower mixed white office shirt for ladies',
      category: 'Shoe',
      image: '/images/Flower mixed white office shirt for ladies3.jpg',
      price: 12500.00,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '4',
      name: 'Ginovo Men Running Shoes',
      slug: 'Ginovo Men Running Shoes',
      category: 'Shoe',
      image: '/images/Ginovo Men Running Shoes.jpg',
      price: 65000,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '1',
      name: 'Gucci Jacket for men',
      slug: 'Gucci Jacket for men',
      category: 'Shirts',
      image: '/images/Gucci Jacket for menp1.jpg', // 679px × 829px
      price: 6700.00,
      countInStock: 10,
      brand: 'Gucci',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Ladybag',
      slug: 'adidas-lady',
      category: 'Shirts',
      image: '/images/lady.jpg',
      price: 25000.00,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '3',
      name: 'ladyjean',
      slug: 'ladyjean',
      category: 'Pants',
      image: '/images/ladyjean.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '3',
      name: 'Stock Ladyjean',
      slug: 'ladyjean',
      category: 'Pants',
      image: '/images/ladyjean.png',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '4',
      name: 'Adidas Lady Top',
      slug: 'adidas-lady top',
      category: 'Lady top',
      image: '/images/ladytop.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '1',
      name: 'menjean',
      slug: 'menjean',
      category: 'Pant',
      image: '/images/menjean.jpg', // 679px × 829px
      price: 9020,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas men Fit Shirt',
      slug: 'adidas-men-fit-shirt',
      category: 'Shirts',
      image: '/images/menshirt.jpg',
      price: 7500.00,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '3',
      name: 'Office Shoe High Heels',
      slug: 'Office Shoe High Heels',
      category: 'Shoe',
      image: '/images/Office Shoe High Heels.jpg',
      price: 45500,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '4',
      name: 'Office Shoe',
      slug: 'Office Shoe',
      category: 'Shoe',
      image: '/images/Office Shoe.jpg',
      price: 65000,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '1',
      name: 'Rosatro Women Full Sleeve Tops Causal V-Neck',
      slug: 'Rosatro Women Full Sleeve Tops Causal V-Neck',
      category: 'Lady',
      image: '/images/Rosatro Women Full Sleeve Tops Causal V-Neck.jpg', // 679px × 829px
      price: 12000.00,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Silk flower top',
      slug: 'Silk flower top',
      category: 'Lady',
      image: '/images/Silk flower top.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '4',
      name: 'Skin Tone Court Shoe',
      slug: 'Skin Tone Court Shoe',
      category: 'Shoe',
      image: '/images/Skin Tone Court Shoe.jpg',
      price: 6500.99,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    }, 
    {
      // _id: '4',
      name: 'Sleeveless-Floral-Top',
      slug: 'Sleeveless-Floral-Top',
      category: 'Shoe',
      image: '/images/Sleeveless-Floral-Top.jpg',
      price: 11500.99,
      countInStock: 4,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    }, 
    {
      // _id: '1',
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 120,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      // _id: '2',
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 0,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '3',
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
    {
      // _id: '4',
      name: 'Adidas Fit Pant',
      slug: 'adidas-fit-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 65,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'Sometimes you just have to keep things simple. No fuss. Easy. Enter this adidas t-shirt. Its one step up from completely minimalist, since there is the bold, contrast adidas graphic that flashes across the chest. But it is something that goes along with your everyday moves, whatever that looks like, and keeps you comfortable along the way (thanks to the soft cotton build). adidas Unisex clothes mixing comfort, style and performance.',
    },
  ],
};
export default data;
